### PR TITLE
Replace HSV comparison with LAB comparison

### LINKED ISSUE #166: FuzzyCompare does not work for similar near-black values
**Describe the bug**

FuzzyCompare does not work for similar near-black values

This issue relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [x] The sample code
- [ ] The documentation

**To Reproduce**

`#010000` converts to `0, 100, 0` in HSV
`#000000` converts to `0, 0, 0` in HSV

There is no visually perceptible difference between these two colours, but the HSV fuzzy comparison algorithm will fail as it interprets the Saturation variation from 0 to 100 as a 100% difference.

The `ScreenshotRuleExampleTests::setExactness` test regularly produces values that should be considered equal, but fail the test.

**Expected behavior**

`ScreenshotRuleExampleTests::setExactness` should pass every time.

**Screenshots**

image

Fuzzy_225
Fuzzy_237

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.5

**Target Android Device (please complete the following information):**
 - Device: Nexus S
-  Physical or Virtual: AVD
 - API Level: 22
- Testify Key: `22-480x800@240dp-en_US`

### PR DESCRIPTION
**Pull request by DanielJette**
### What does this change accomplish?

Resolves #166 - FuzzyCompare does not work for similar near-black values
Replace HSV comparison with LAB comparison

### How have you achieved it?

The existing `FuzzyCompare` uses an HSV-based color-difference algorithm. Unfortunately, this algorithm has clear weaknesses with near-black values.

e.g.
`#010000` converts to `0, 100, 0` in HSV
`#000000` converts to `0, 0, 0` in HSV

There is no visually perceptible difference between these two colours, but the HSV fuzzy comparison algorithm will fail as it interprets the Saturation variation from 0 to 100 as a 100% difference.

The `ScreenshotRuleExampleTests::setExactness` test regularly produces values that should be considered equal, but fail the test.

This PR replaces the existing HSV difference calculation with calculating the colour difference value between two colours in LAB space.

The **CIELAB** color space (also known as CIE L* a* b* or sometimes abbreviated as simply "Lab" color space) is a color space defined by the _International Commission on Illumination_ (CIE) in 1976. It expresses color as three values: L* for the lightness from black (0) to white (100), a* from green (−) to red (+), and b* from blue (−) to yellow (+). CIELAB was designed so that the same amount of numerical change in these values corresponds to roughly the same amount of visually perceived change.

The CIE calls their distance metric ΔE*ab where delta is a Greek letter often used to denote difference, and E stands for _Empfindung_; German for "sensation".

If deltaE < 1 then the difference can't recognized by human eyes.

https://en.wikipedia.org/wiki/Color_difference#CIEDE2000

### Tophat instructions

I have have added both instrumentation tests (`FuzzyCompareBitmapTest`) and JVM tests (`FuzzyCompareTest`) to the Library as updated the Sample tests.

### Notice

This change must keep `master` in a shippable state; **it may be shipped without further notice**.

### CODE REVIEW

File: Library/src/main/java/com/shopify/testify/internal/compare/colorspace/DeltaE.kt [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+ *
+ * @param L1 first colour's L component
+ * @param a1 first colour's a component
+ * @param b1 first colour's b component
+ * @param L2 second colour's L component
+ * @param a2 second colour's a component
+ * @param b2 second colour's b component
+ * @return the CIE 2000 colour difference
+ */
+fun calculateDeltaE(L1: Double, a1: Double, b1: Double, L2: Double, a2: Double, b2: Double): Double {
```
Comment (fredells) [inline Library/src/main/java/com/shopify/testify/internal/compare/colorspace/DeltaE.kt:59]: Is this not part of the lib?

File: Sample/src/androidTest/java/com/shopify/testify/sample/ScreenshotRuleExampleTests.kt [hunk 2]
```diff
@@ -216,6 +216,9 @@ class ScreenshotRuleExampleTests {
     @Test
     fun setExactness() {
         rule
+            .setScreenshotViewProvider {
+                it.findViewById(R.id.info_card)
+            }
             .setExactness(0.9f)
```
Comment (fredells) [inline Sample/src/androidTest/java/com/shopify/testify/sample/ScreenshotRuleExampleTests.kt:222]: We can maybe set this higher now? 0.9 seems quite low

File: Library/src/test/java/com/shopify/testify/FuzzyCompareTest.kt [hunk 3]
```diff
@@ -23,89 +23,133 @@
...
     }
 
     @Test
-    fun hues5PercentDifferentWith5PercentTolerance() {
-        for (hue in 0..359) {
-            assertFalse(FuzzyCompare.isHueDifferent(hue.toFloat(), (hue + 18).toFloat(), 0.95f))
+    fun redDifferenceLab() {
+        // Visually very similar Red-based colors
+        (0..20).forEach { value1 ->
+            val baseColor = RGB(255 - value1, value1, value1)
```
Comment (fredells) [inline Library/src/test/java/com/shopify/testify/FuzzyCompareTest.kt:93]: did you mean to pass `value1` for non Red values? same q for the other colour tests

File: Sample/src/androidTest/java/com/shopify/testify/sample/ScreenshotRuleExampleTests.kt (hunk 2 above)
Comment (DanielJette) [reply Sample/src/androidTest/java/com/shopify/testify/sample/ScreenshotRuleExampleTests.kt:222]: You're right. It can be higher. I'll update it

File: Library/src/test/java/com/shopify/testify/FuzzyCompareTest.kt (hunk 3 above)
Comment (DanielJette) [reply Library/src/test/java/com/shopify/testify/FuzzyCompareTest.kt:93]: Yes, this is intentional.

This generates visibly "red" colours in the range of `#EB0000` to `#FF1414`. I vary the G and B component by up to 20 because, so long as the R component dominates significantly, that slight amount of other colour still looks very "red".

File: Library/src/main/java/com/shopify/testify/internal/compare/colorspace/DeltaE.kt (hunk 1 above)
Comment (DanielJette) [reply Library/src/main/java/com/shopify/testify/internal/compare/colorspace/DeltaE.kt:59]: OK. It does not. I thought I was going crazy. I had found the deltaE conversion on wikipedia and was looking for some RGB --> LAB conversion code and found this `colormath` library. I'm only using the lib for colorspace conversions. I checked and they don't have any methods for difference or deltaE.

But, now that I see this, I wonder if the author of that library would find the `deltaE` calculation useful? It might be worth PR'ing that.
