### PR TITLE
Fixed issue #153 - Orientation change will now be reliably applied

### LINKED ISSUE #153: Beta 3: setOrientation does not work if used in consecutive tests
## Repro steps

The following will not work:

```kotlin
    @TestifyLayout(R.layout.view_client_details)
    @ScreenshotInstrumentation
    @Test
    fun a() {
        rule
            .setOrientation(requestedOrientation = SCREEN_ORIENTATION_LANDSCAPE)
            .assertSame()
    }

    @TestifyLayout(R.layout.view_client_details)
    @ScreenshotInstrumentation
    @Test
    fun b() {
        rule
            .setOrientation(requestedOrientation = SCREEN_ORIENTATION_LANDSCAPE)
            .assertSame()
    }

```

The second test (`b()`) will not rotate into landscape

### PR DESCRIPTION
**Pull request by DanielJette**
## What?

Resolves #153 
Orientation change will now be reliably applied regardless of how many times you invoke `setOrientation` in a single test class.

## What was the problem?

Android's recommended way of programatically changing the orientation of an Activity is to invoke [`setRequestedOrientation`](https://developer.android.com/reference/android/app/Activity#setRequestedOrientation(int))

>Change the desired orientation of this activity. If the activity is currently in the foreground or otherwise impacting the screen orientation, the screen will immediately be changed (possibly causing the activity to be restarted). Otherwise, this will be used the next time the activity is visible.

After some significant debugging, I determined that invoking `setRequestedOrientation` is not a blocking/synchronous call as it requires the Activity to go through the full recreation lifecycle. Testify had previously used `Espresso.onIdle()` to synchronize the test thread and ui thread, but this was not sufficient. In many cases, the orientation change did not complete before the first idle loop. This lead to flaky tests and failures in setting the orientation.
Typically, this would manifest itself by Testify either capturing the screenshot of the pre-rotation state (holding on to a reference of the original activity instance) or by capturing a white screen (capturing the bitmap before the rotation was fully complete).

## How was this fixed?

1. Wait for the activity to `RESUME` before continuing. This is the key change. An `ActivityLifecycleMonitor` is now installed when an orientation change is requested. We block the test thread until the Activity returns to the Resumed state after requesting an orientation change.
1. Remove the `ActivityMonitor`. The use of the ActivityMonitor goes back to the JUnit3 version of Testify. At that time, Testify used the now-deprecated `ActivityInstrumentationTestCase2` as a base class. This required the use of the `ActivityMonitor` in order to track the new instance of the Activity created after rotation. Testify now uses the JUnit4 `ActivityTestRule` and this class is built to understand the lifecycle of activities under test and will always return the correct Activity instance. See [`getActivity`](https://developer.android.com/reference/androidx/test/rule/ActivityTestRule#getActivity())
    > During the duration of the test you will be able to manipulate your Activity directly using the reference obtained from getActivity(). If the Activity is finished and relaunched, the reference returned by getActivity() will always point to the current instance of the Activity. 
1. Add some error detection. Detect if the orientation change failed and report accordingly. This will help in diagnosing future problems.
1. Move all the orientation-related code to `OrientationHelper`

## Tophat

- Run the tests in `OrientationTest` on the Sample app
- Note that you'll probably have to record a baseline for those tests on your emulator
- You can also use the emulator configuration described here https://github.com/Shopify/android-testify/blob/master/RECIPES.md#setting-up-an-emulator-to-run-the-sample

### CODE REVIEW

File: Library/src/main/java/com/shopify/testify/internal/helpers/OrientationHelper.kt [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+
+        this.runOnUiThread {
+            this.requestedOrientation = requestedOrientation
+            rotationLatch.countDown()
+        }
+
+        // Wait for the rotation request to be made
+        if (!rotationLatch.await(1, TimeUnit.SECONDS)) {
+            throw UnexpectedOrientationException("Failed to apply requested rotation.")
+        }
```
Comment (fredells) [inline Library/src/main/java/com/shopify/testify/internal/helpers/OrientationHelper.kt:115]: failing to understand this. we update an int var on the ui thread and then unlock the latch. what actually causes the the config change here

Comment (DanielJette) [reply Library/src/main/java/com/shopify/testify/internal/helpers/OrientationHelper.kt:115]: @fredells `requestedOrientation` is the kotlin property syntax for `setRequestedOrientation`
It's a method, not a property
It calls this https://developer.android.com/reference/android/app/Activity#setRequestedOrientation(int)
