### PR TITLE
Fix issue 138: Introduce the `setFocusTarget` method on `ScreenshotRule` which allows for keyboard focus to be placed on an explicit View

### LINKED ISSUE #138: Investigate: Focus is inconsistently applied to Views, causing test flakiness
After running several tests, particularly on higher API levels, you might not some elements appear to be focused or selected. This happens randomly and inconsistently and causes significant flakiness.

Consider a mechanism to force the focus consistently on every test run.

### PR DESCRIPTION
**Pull request by DanielJette**
### What does this change accomplish?

Resolves #138 
Introduce the `setFocusTarget` method on `ScreenshotRule` which allows for keyboard focus to be placed on an explicit View

### How have you achieved it?

While investigating #138, I determined that the keyboard focus is seemingly applied at random while test. What I observed was that the focus highlight is frequently applied to the OS Launcher background (normally the clock) and that, when this is present, focus will be transferred to the default view in the hierarchy of your Activity under test. This means that test rendering is dependant on both the nature of your layout (does it render a focus highlight?) and whether the OS currently is displaying focus. In order to give control to the developer, this PR adds a `setFocusTarget` method to `ScreenshotRule` which can be used to explicitly request focus on the provided view. This guarantees that consistent rendering.

Tip: Request focus on `android.R.id.content` to create the appearance that nothing is selected.

### Tophat instructions

It's possible that users can navigate your app using a keyboard, because the Android system enables most of the necessary behaviors by default.
In order to place the keyboard focus on a specific View, use the `setFocusTarget` method.

See https://developer.android.com/training/keyboard-input/navigation

```kotlin
    @ScreenshotInstrumentation
    @Test
    fun default() {
        rule
            .setFocusTarget(enabled = true, focusTargetId = R.id.fab)
            .assertSame()
    }
```

### Notice

This change must keep `master` in a shippable state; **it may be shipped without further notice**.

### CODE REVIEW

File: Library/src/main/java/com/shopify/testify/internal/modification/FocusModification.kt [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+        activity.runOnUiThread {
+            performModification(activity.getFocusTargetView())
+
+            threadLatch.countDown()
+            Handler(Looper.getMainLooper()).postDelayed({
+                threadLatch.countDown()
+            }, 250)
+        }
+
+        threadLatch.await(5, TimeUnit.SECONDS)
```
Comment (lwise) [inline Library/src/main/java/com/shopify/testify/internal/modification/FocusModification.kt:64]: Just curious as to why 5 seconds as that seems pretty long

Comment (DanielJette) [reply Library/src/main/java/com/shopify/testify/internal/modification/FocusModification.kt:64]: I could really have chosen any number, but I didn't want to repeat the issues I encountered with the Orientation change bugs. Basically, I need to wait for the Activity to go idle. Depending on what other commands are invoke, maybe espresso or an orientation change, this can take a couple seconds. In reality, it probably doesn't matter and this will complete in a couple hundred milliseconds, but this way, if it does drag on, I won't be failing the test because my timeout was too short
